@api_HostAddress = http://localhost:5023

POST {{api_HostAddress}}/api/user/register
Content-Type: application/json

{
    "name": "João Lucas",
    "email": "joaolucas",
    "password": "12346789"
}

###
